// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	customer "auth-with-clean-architecture/internal/customer"

	mock "github.com/stretchr/testify/mock"
)

// ControllerInterface is an autogenerated mock type for the ControllerInterface type
type ControllerInterface struct {
	mock.Mock
}

type ControllerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ControllerInterface) EXPECT() *ControllerInterface_Expecter {
	return &ControllerInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: body
func (_m *ControllerInterface) Create(body *customer.CreateRequest) (*customer.CustomerItemResponse, error) {
	ret := _m.Called(body)

	var r0 *customer.CustomerItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(*customer.CreateRequest) (*customer.CustomerItemResponse, error)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(*customer.CreateRequest) *customer.CustomerItemResponse); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.CustomerItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*customer.CreateRequest) error); ok {
		r1 = rf(body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ControllerInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - body *customer.CreateRequest
func (_e *ControllerInterface_Expecter) Create(body interface{}) *ControllerInterface_Create_Call {
	return &ControllerInterface_Create_Call{Call: _e.mock.On("Create", body)}
}

func (_c *ControllerInterface_Create_Call) Run(run func(body *customer.CreateRequest)) *ControllerInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*customer.CreateRequest))
	})
	return _c
}

func (_c *ControllerInterface_Create_Call) Return(_a0 *customer.CustomerItemResponse, _a1 error) *ControllerInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_Create_Call) RunAndReturn(run func(*customer.CreateRequest) (*customer.CustomerItemResponse, error)) *ControllerInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function with given fields: ID
func (_m *ControllerInterface) Destroy(ID string) (*customer.CustomerItemResponse, error) {
	ret := _m.Called(ID)

	var r0 *customer.CustomerItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*customer.CustomerItemResponse, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *customer.CustomerItemResponse); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.CustomerItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type ControllerInterface_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ID string
func (_e *ControllerInterface_Expecter) Destroy(ID interface{}) *ControllerInterface_Destroy_Call {
	return &ControllerInterface_Destroy_Call{Call: _e.mock.On("Destroy", ID)}
}

func (_c *ControllerInterface_Destroy_Call) Run(run func(ID string)) *ControllerInterface_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ControllerInterface_Destroy_Call) Return(_a0 *customer.CustomerItemResponse, _a1 error) *ControllerInterface_Destroy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_Destroy_Call) RunAndReturn(run func(string) (*customer.CustomerItemResponse, error)) *ControllerInterface_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Show provides a mock function with given fields: ID
func (_m *ControllerInterface) Show(ID string) (*customer.CustomerItem, error) {
	ret := _m.Called(ID)

	var r0 *customer.CustomerItem
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*customer.CustomerItem, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *customer.CustomerItem); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.CustomerItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type ControllerInterface_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
//   - ID string
func (_e *ControllerInterface_Expecter) Show(ID interface{}) *ControllerInterface_Show_Call {
	return &ControllerInterface_Show_Call{Call: _e.mock.On("Show", ID)}
}

func (_c *ControllerInterface_Show_Call) Run(run func(ID string)) *ControllerInterface_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ControllerInterface_Show_Call) Return(_a0 *customer.CustomerItem, _a1 error) *ControllerInterface_Show_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_Show_Call) RunAndReturn(run func(string) (*customer.CustomerItem, error)) *ControllerInterface_Show_Call {
	_c.Call.Return(run)
	return _c
}

// ShowAll provides a mock function with given fields:
func (_m *ControllerInterface) ShowAll() (*[]customer.CustomerItem, error) {
	ret := _m.Called()

	var r0 *[]customer.CustomerItem
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]customer.CustomerItem, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]customer.CustomerItem); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]customer.CustomerItem)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_ShowAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowAll'
type ControllerInterface_ShowAll_Call struct {
	*mock.Call
}

// ShowAll is a helper method to define mock.On call
func (_e *ControllerInterface_Expecter) ShowAll() *ControllerInterface_ShowAll_Call {
	return &ControllerInterface_ShowAll_Call{Call: _e.mock.On("ShowAll")}
}

func (_c *ControllerInterface_ShowAll_Call) Run(run func()) *ControllerInterface_ShowAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ControllerInterface_ShowAll_Call) Return(_a0 *[]customer.CustomerItem, _a1 error) *ControllerInterface_ShowAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_ShowAll_Call) RunAndReturn(run func() (*[]customer.CustomerItem, error)) *ControllerInterface_ShowAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ID, body
func (_m *ControllerInterface) Update(ID string, body customer.Customer) (*customer.CustomerItemResponse, error) {
	ret := _m.Called(ID, body)

	var r0 *customer.CustomerItemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, customer.Customer) (*customer.CustomerItemResponse, error)); ok {
		return rf(ID, body)
	}
	if rf, ok := ret.Get(0).(func(string, customer.Customer) *customer.CustomerItemResponse); ok {
		r0 = rf(ID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.CustomerItemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, customer.Customer) error); ok {
		r1 = rf(ID, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ControllerInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ControllerInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ID string
//   - body customer.Customer
func (_e *ControllerInterface_Expecter) Update(ID interface{}, body interface{}) *ControllerInterface_Update_Call {
	return &ControllerInterface_Update_Call{Call: _e.mock.On("Update", ID, body)}
}

func (_c *ControllerInterface_Update_Call) Run(run func(ID string, body customer.Customer)) *ControllerInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(customer.Customer))
	})
	return _c
}

func (_c *ControllerInterface_Update_Call) Return(_a0 *customer.CustomerItemResponse, _a1 error) *ControllerInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ControllerInterface_Update_Call) RunAndReturn(run func(string, customer.Customer) (*customer.CustomerItemResponse, error)) *ControllerInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewControllerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewControllerInterface creates a new instance of ControllerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewControllerInterface(t mockConstructorTestingTNewControllerInterface) *ControllerInterface {
	mock := &ControllerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
