// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	customer "auth-with-clean-architecture/internal/customer"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface struct {
	mock.Mock
}

type RepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryInterface) EXPECT() *RepositoryInterface_Expecter {
	return &RepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: body
func (_m *RepositoryInterface) Create(body *customer.Customer) error {
	ret := _m.Called(body)

	var r0 error
	if rf, ok := ret.Get(0).(func(*customer.Customer) error); ok {
		r0 = rf(body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - body *customer.Customer
func (_e *RepositoryInterface_Expecter) Create(body interface{}) *RepositoryInterface_Create_Call {
	return &RepositoryInterface_Create_Call{Call: _e.mock.On("Create", body)}
}

func (_c *RepositoryInterface_Create_Call) Run(run func(body *customer.Customer)) *RepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*customer.Customer))
	})
	return _c
}

func (_c *RepositoryInterface_Create_Call) Return(_a0 error) *RepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RepositoryInterface_Create_Call) RunAndReturn(run func(*customer.Customer) error) *RepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Destroy provides a mock function with given fields: ID
func (_m *RepositoryInterface) Destroy(ID string) (*customer.Customer, error) {
	ret := _m.Called(ID)

	var r0 *customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*customer.Customer, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *customer.Customer); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterface_Destroy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destroy'
type RepositoryInterface_Destroy_Call struct {
	*mock.Call
}

// Destroy is a helper method to define mock.On call
//   - ID string
func (_e *RepositoryInterface_Expecter) Destroy(ID interface{}) *RepositoryInterface_Destroy_Call {
	return &RepositoryInterface_Destroy_Call{Call: _e.mock.On("Destroy", ID)}
}

func (_c *RepositoryInterface_Destroy_Call) Run(run func(ID string)) *RepositoryInterface_Destroy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RepositoryInterface_Destroy_Call) Return(_a0 *customer.Customer, _a1 error) *RepositoryInterface_Destroy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterface_Destroy_Call) RunAndReturn(run func(string) (*customer.Customer, error)) *RepositoryInterface_Destroy_Call {
	_c.Call.Return(run)
	return _c
}

// Show provides a mock function with given fields: ID
func (_m *RepositoryInterface) Show(ID string) (*customer.Customer, error) {
	ret := _m.Called(ID)

	var r0 *customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*customer.Customer, error)); ok {
		return rf(ID)
	}
	if rf, ok := ret.Get(0).(func(string) *customer.Customer); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterface_Show_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Show'
type RepositoryInterface_Show_Call struct {
	*mock.Call
}

// Show is a helper method to define mock.On call
//   - ID string
func (_e *RepositoryInterface_Expecter) Show(ID interface{}) *RepositoryInterface_Show_Call {
	return &RepositoryInterface_Show_Call{Call: _e.mock.On("Show", ID)}
}

func (_c *RepositoryInterface_Show_Call) Run(run func(ID string)) *RepositoryInterface_Show_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RepositoryInterface_Show_Call) Return(_a0 *customer.Customer, _a1 error) *RepositoryInterface_Show_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterface_Show_Call) RunAndReturn(run func(string) (*customer.Customer, error)) *RepositoryInterface_Show_Call {
	_c.Call.Return(run)
	return _c
}

// ShowAll provides a mock function with given fields:
func (_m *RepositoryInterface) ShowAll() ([]customer.Customer, error) {
	ret := _m.Called()

	var r0 []customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]customer.Customer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []customer.Customer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterface_ShowAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowAll'
type RepositoryInterface_ShowAll_Call struct {
	*mock.Call
}

// ShowAll is a helper method to define mock.On call
func (_e *RepositoryInterface_Expecter) ShowAll() *RepositoryInterface_ShowAll_Call {
	return &RepositoryInterface_ShowAll_Call{Call: _e.mock.On("ShowAll")}
}

func (_c *RepositoryInterface_ShowAll_Call) Run(run func()) *RepositoryInterface_ShowAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryInterface_ShowAll_Call) Return(_a0 []customer.Customer, _a1 error) *RepositoryInterface_ShowAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterface_ShowAll_Call) RunAndReturn(run func() ([]customer.Customer, error)) *RepositoryInterface_ShowAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ID, body
func (_m *RepositoryInterface) Update(ID string, body customer.Customer) (*customer.Customer, error) {
	ret := _m.Called(ID, body)

	var r0 *customer.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string, customer.Customer) (*customer.Customer, error)); ok {
		return rf(ID, body)
	}
	if rf, ok := ret.Get(0).(func(string, customer.Customer) *customer.Customer); ok {
		r0 = rf(ID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string, customer.Customer) error); ok {
		r1 = rf(ID, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ID string
//   - body customer.Customer
func (_e *RepositoryInterface_Expecter) Update(ID interface{}, body interface{}) *RepositoryInterface_Update_Call {
	return &RepositoryInterface_Update_Call{Call: _e.mock.On("Update", ID, body)}
}

func (_c *RepositoryInterface_Update_Call) Run(run func(ID string, body customer.Customer)) *RepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(customer.Customer))
	})
	return _c
}

func (_c *RepositoryInterface_Update_Call) Return(_a0 *customer.Customer, _a1 error) *RepositoryInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RepositoryInterface_Update_Call) RunAndReturn(run func(string, customer.Customer) (*customer.Customer, error)) *RepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRepositoryInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryInterface creates a new instance of RepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryInterface(t mockConstructorTestingTNewRepositoryInterface) *RepositoryInterface {
	mock := &RepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
