version: '${TAG_VERSION}'
services:
    "${DOCKERHUB_REPOSITORY}-mysql":
        container_name: ${DOCKERHUB_REPOSITORY}-mysql
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USERNAME}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
        volumes:
            - ${DOCKERHUB_REPOSITORY}:/var/lib/mysql
            - ../docs:/docker-entrypoint-initdb.d
        networks:
            - ${DOCKERHUB_REPOSITORY}
    "${DOCKERHUB_REPOSITORY}-go":
        container_name: ${DOCKERHUB_REPOSITORY}-go
        image: ${DOCKERHUB_REPOSITORY}:${TAG_VERSION}
        # restart: always
        build:
            context: ..
            dockerfile: deployments/Dockerfile
        ports:
            - 8081:8080
        environment:
            - DB_HOST=${DOCKERHUB_REPOSITORY}-mysql
            - DB_PORT=${MYSQL_PORT}
            - DB_USERNAME=${MYSQL_USERNAME}
            - DB_PASSWORD=${MYSQL_PASSWORD}
            - DB_DATABASE=${MYSQL_DATABASE}
            - JWT_KEY=${JWT_KEY}
        networks:
            - ${DOCKERHUB_REPOSITORY}
        depends_on:
            - ${DOCKERHUB_REPOSITORY}-mysql
volumes:
    "${DOCKERHUB_REPOSITORY}":
        driver: local
networks:
    "${DOCKERHUB_REPOSITORY}":
        driver: bridge
