version: '2.0'
services:
    awca-mysql:
        container_name: awca-mysql
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=auth_with_clean_architecture
        volumes:
            - awca:/var/lib/mysql
            - ../docs:/docker-entrypoint-initdb.d
        networks:
            - awca
    awca-go:
        container_name: awca-go
        image: awca:2.0
        # restart: always
        build:
            context: ..
            dockerfile: deployments/Dockerfile
        ports:
            - 1337:8080
        environment:
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - DB_HOST=awca-mysql
            - DB_PORT=3306
            - DB_DATABASE=auth_with_clean_architecture
            - JWT_KEY=secret-key
        networks:
            - awca
        depends_on:
            - awca-mysql
volumes:
    awca:
networks:
    awca:
