name: Production

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        run: |
          sed -i 's/${DOCKERHUB_USERNAME}/${{ vars.DOCKERHUB_USERNAME }}/g' deployments/docker-compose.yaml
          sed -i 's/${DOCKERHUB_REPOSITORY}/${{ vars.DOCKERHUB_REPOSITORY }}/g' deployments/docker-compose.yaml
          sed -i 's/${TAG_VERSION}/${{ vars.TAG_VERSION }}/g' deployments/docker-compose.yaml
          sed -i 's/${PORT}/${{ vars.PORT }}/g' deployments/docker-compose.yaml
          sed -i 's/${MYSQL_ROOT_PASSWORD}/${{ secrets.MYSQL_ROOT_PASSWORD }}/g' deployments/docker-compose.yaml
          sed -i 's/${MYSQL_USERNAME}/${{ vars.MYSQL_USERNAME }}/g' deployments/docker-compose.yaml
          sed -i 's/${MYSQL_PASSWORD}/${{ secrets.MYSQL_PASSWORD }}/g' deployments/docker-compose.yaml
          sed -i 's/${MYSQL_DATABASE}/${{ vars.MYSQL_DATABASE }}/g' deployments/docker-compose.yaml
          sed -i 's/${JWT_KEY}/${{ secrets.JWT_SECRET_KEY }}/g' deployments/docker-compose.yaml
          docker-compose -f ./deployments/docker-compose.yaml build
          docker-compose -f ./deployments/docker-compose.yaml push

  # deploy:
  #   name: Deploy to VPS
  #   runs-on: ubuntu-latest
  #   needs: [docker]
  #   steps:
  #     - name: Deploy to VPS
  #       uses: appleboy/ssh-action@v0.1.4
  #       with:
  #         host: ${{ vars.SSH_HOST }}
  #         port: ${{ vars.SSH_PORT }}
  #         username: ${{ vars.SSH_USERNAME }}
  #         password: ${{ secrets.SSH_PASSWORD }}
  #         # key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           docker stop ${{ vars.DOCKERHUB_REPOSITORY }}-go || true
  #           docker rm ${{ vars.DOCKERHUB_REPOSITORY }}-go || true
  #           docker pull ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:${{ vars.TAG_VERSION }}
  #           docker run -d \
  #             --name ${{ vars.DOCKERHUB_REPOSITORY }}-go \
  #             -e DB_HOST=${{ vars.DOCKERHUB_REPOSITORY }}-mysql \
  #             -e DB_PORT=3306 \
  #             -e DB_USERNAME=${{ vars.MYSQL_USERNAME }} \
  #             -e DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
  #             -e DB_DATABASE=${{ vars.MYSQL_DATABASE }} \
  #             -e JWT_KEY=${{ secrets.JWT_SECRET_KEY }} \
  #             -p ${{ vars.PORT }}:8080 \
  #             --network=${{ vars.DOCKERHUB_REPOSITORY }} \
  #             ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY }}:${{ vars.TAG_VERSION }}
